version: '3'

services:
  mariabd:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=morasha
      - MARIADB_DATABASE=morasha
      - MARIADB_USER=morasha
      - MARIADB_PASSWORD=morasha
    volumes:
      - ./data:/var/lib/mysql
    expose:
      - 3306

  backend:
    build:
      context: ./morasha
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - 'mariabd'
    environment:
      - DJANGO_SUPERUSER_PASSWORD=morasha
      - DJANGO_SUPERUSER_USERNAME=morasha
      - DJANGO_SUPERUSER_EMAIL=morasha@gmail.com
    ports:
      - 7000:7000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:7000 --noreload"

networks:
  default:
    external:
      name: nginx-networks