# Generated by Django 5.0.6 on 2024-06-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(verbose_name='Пользователь')),
                ('question_name', models.TextField(verbose_name='Номер вопроса')),
                ('answer', models.TextField(verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.IntegerField(verbose_name='ID ссылки')),
                ('question_name', models.TextField(verbose_name='Номер вопроса')),
                ('question', models.TextField(verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос для ивента',
                'verbose_name_plural': 'Вопросы для ивента',
            },
        ),
    ]
