# Generated by Django 5.0.6 on 2024-06-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventusers',
            name='user_name',
            field=models.TextField(unique=True, verbose_name='Имя'),
        ),
    ]
