# Generated by Django 5.0.6 on 2024-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventusers_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='sort_id',
            field=models.IntegerField(default=1, verbose_name='id for sort'),
            preserve_default=False,
        ),
    ]
